
[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'object-manager'
Port = 5000
Protocol = 'http'
MaxResultCount = 50000
StartupMsg = 'This is the Object Manager Microservice'
Timeout = 5000

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = true
File = '/edgex/logs/object-manager.log'


[Clients]
  [Clients.Notifications]
  Protocol = 'http'
  Host = 'edgex-support-notifications'
  Port = 48060

  [Clients.Command]
  Protocol = 'http'
  Host = 'edgex-core-command'
  Port = 48082

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'edgex-core-metadata'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'edgex-support-logging'
  Port = 48061

  [Clients.Data]
  Protocol = 'http'
  Host = 'edgex-core-data'
  Port = 48080

  [Clients.Scheduler]
  Protocol = 'http'
  Host = 'edgex-support-scheduler'
  Port = 48085

  [Clients.Export]
  Protocol = 'http'
  Host = 'edgex-export-client'
  Port = 48071

  [Clients.Distro]
  Protocol = 'http'
  Host = 'edgex-export-distro'
  Port = 48070
